openapi: 3.0.0
info:
  title: API de conexión
  description: Documentación de la API para la gestión de facturas y transacciones en la red Lightning Network
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Servidor de desarrollo

paths:
  /generate-invoice:
    post:
      summary: Generar una factura
      requestBody:
        description: Datos necesarios para generar una factura
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  example: 1000
                  description: Cantidad en satoshis (admite milisatoshis)
                expiration:
                  type: integer
                  example: 900
                  description: Tiempo de expiración de la factura en segundos
                memo:
                  type: string
                  example: Pago de prueba
                  description: Memo que acompaña a la solicitud de factura
      responses:
        '200':
          description: Factura generada con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  invoice:
                    type: string
                    example: lnbc1u1pwuf73o5jfuc62jdk93urofkap...  # Ejemplo de una factura Lightning Network
                    description: La factura generada
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor

components:
  schemas:
    InvoiceRequest:
      type: object
      required:
        - amount
        - expiration
        - memo
      properties:
        amount:
          type: number
          description: Monto en satoshis
        expiration:
          type: integer
          description: Tiempo de expiración en segundos
        memo:
          type: string
          description: Descripción de la factura

    InvoiceResponse:
      type: object
      properties:
        invoice:
          type: string
          description: La factura generada
